# _*_ restclient _*_
#
## random projection

GET https://localhost:3131/api/random/projection/
Accept: application/transit+json

## specific projection

GET http://localhost:3131/api/stack?entity=aqua
Accept: application/transit+json

## session submission

POST http://localhost:3131/api/submit/session
Accept: application/transit+json
Content-Type: application/transit+json

["^ ","~:session/id","~ueb5fb212-5d24-4642-94e7-99ba0696af93","~:session/entity","~:entity/aqua"]: 
